# Folds tricks.json + front.json into js/data.js for the site.
import json, re, io, os

OUT = r"C:\Users\dangeratio\Documents\development\claudecode\thetricktionary.github.io\js\data.js"

tricks = json.load(open("tricks.json", encoding="utf-8"))
front = json.load(open("front.json", encoding="utf-8"))


def slug(name):
    s = name.lower().replace("&", "and").replace("+", " plus ")
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s


by_name = {}
for t in tricks:
    t["slug"] = slug(t["name"])
    by_name[t["name"].lower()] = t["slug"]

# Cross-link the "variations" and "related tricks" boxes to real pages where
# the named trick has one of its own. Many variations are described in prose
# only and never get a page; those stay as plain text.
linked = 0
for t in tricks:
    for grp in ("variations", "related"):
        for row in t[grp]:
            s = by_name.get(row["name"].lower())
            if s and s != t["slug"]:
                row["slug"] = s
                linked += 1

# The non-text half of a book page: per-step stick inputs, the originator
# credit, and the URLs behind the printed source labels. Optional, so this
# tool still runs from the two checked-in PDF extracts alone.
enriched = 0
try:
    inputs = json.load(open("inputs.json", encoding="utf-8"))
except IOError:
    inputs = {}
    print("note: inputs.json missing, entries will have no stick diagrams")
for t in tricks:
    extra = inputs.get(t["slug"])
    if not extra:
        continue
    t.update(extra)
    enriched += 1

order = ["Beginner", "Novice", "Intermediate", "Advanced", "Master"]
tricks.sort(key=lambda t: (order.index(t["difficulty"]), t["page"] or 0))

for tier in front["progression"]:
    for item in tier["items"]:
        item["slug"] = by_name[item["name"].lower()]

data = {
    "tricks": tricks,
    "glossary": front["glossary"],
    "progression": front["progression"],
    "sources": front["sources"],
}

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("/* Generated by tools/build-data.py from the-tricktionary-v1.pdf.\n")
    f.write("   Do not hand-edit: re-run the tool instead. */\n")
    for key in ("tricks", "glossary", "progression", "sources"):
        f.write("const %s = %s;\n" % (key.upper(),
                json.dumps(data[key], ensure_ascii=False, separators=(",", ":"))))

print("%d tricks (%d enriched), %d cross-links, %d glossary, %d sources -> %.0f KB"
      % (len(tricks), enriched, linked, len(front["glossary"]), len(front["sources"]),
         os.path.getsize(OUT) / 1024))
