# Folds tricks.json + front.json into js/data.js for the site.
import json, re, io, os

OUT = r"C:\Users\dangeratio\Documents\development\claudecode\thetricktionary.github.io\js\data.js"

tricks = json.load(open("tricks.json", encoding="utf-8"))
front = json.load(open("front.json", encoding="utf-8"))


def slug(name):
    s = name.lower().replace("&", "and").replace("+", " plus ")
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s


# Tricks the book does not have. The PDF extractors rewrite tricks.json wholesale
# from the printed pages, so anything hand-authored has to live outside it or it
# would be lost the next time the book is re-read. Same shape as a book trick,
# plus addedOnSite, and with page/pdfPage null since there is no page to link to.
try:
    extra_tricks = json.load(open("extra-tricks.json", encoding="utf-8"))
except IOError:
    extra_tricks = []
tricks += extra_tricks

by_name = {}
for t in tricks:
    t["slug"] = slug(t["name"])
    by_name[t["name"].lower()] = t["slug"]

# ---------------------------------------------------------------- slug guard
# Mastery stars in a user's browser are keyed by slug, so a slug that changes
# or disappears between builds silently orphans that trick's progress. Compare
# against the data.js already committed and refuse to write a build that drops
# one without an alias to carry it over. Runs before anything else touches the
# slugs, so a rename reports this rather than failing later on a lookup.
#
# SLUG_ALIASES maps an old slug to the slug that replaced it. app.js applies it
# on load and rewrites storage, so a rename costs nobody their stars. Entries
# are cheap and must never be deleted: a user who has not opened the site since
# before the rename still needs the hop.
SLUG_ALIASES = {
    # "old-slug": "new-slug",
}

previous = set()
if os.path.exists(OUT):
    with io.open(OUT, encoding="utf-8") as f:
        previous = set(re.findall(r'"slug":"([^"]+)"', f.read()))

current = {t["slug"] for t in tricks}
dropped = sorted(s for s in previous - current if s not in SLUG_ALIASES)
if dropped:
    raise SystemExit(
        "refusing to build: %d slug(s) from the last build have gone and have no\n"
        "SLUG_ALIASES entry, so anyone with progress on them would lose it:\n"
        "  %s\n"
        "Add each to SLUG_ALIASES in this file, mapping it to its replacement."
        % (len(dropped), "\n  ".join(dropped)))
renamed = {k: v for k, v in SLUG_ALIASES.items() if v in current}

# Cross-link the "variations" and "related tricks" boxes to real pages where
# the named trick has one of its own. Many variations are described in prose
# only and never get a page; those stay as plain text.
linked = 0
for t in tricks:
    for grp in ("variations", "related"):
        for row in t[grp]:
            s = by_name.get(row["name"].lower())
            if s and s != t["slug"]:
                row["slug"] = s
                linked += 1

# The non-text half of a book page: per-step stick inputs, the originator
# credit, and the URLs behind the printed source labels. Optional, so this
# tool still runs from the two checked-in PDF extracts alone.
enriched = 0
try:
    inputs = json.load(open("inputs.json", encoding="utf-8"))
except IOError:
    inputs = {}
    print("note: inputs.json missing, entries will have no stick diagrams")
for t in tricks:
    extra = inputs.get(t["slug"])
    if not extra:
        continue
    t.update(extra)
    enriched += 1

order = ["Beginner", "Novice", "Intermediate", "Advanced", "Master"]
tricks.sort(key=lambda t: (order.index(t["difficulty"]), t["page"] or 0))

for tier in front["progression"]:
    for item in tier["items"]:
        item["slug"] = by_name[item["name"].lower()]

data = {
    "tricks": tricks,
    "glossary": front["glossary"],
    "progression": front["progression"],
    "sources": front["sources"],
}

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("/* Generated by tools/build-data.py from the-tricktionary-v1.pdf.\n")
    f.write("   Do not hand-edit: re-run the tool instead. */\n")
    f.write("const SLUG_ALIASES = %s;\n"
            % json.dumps(renamed, ensure_ascii=False, separators=(",", ":")))
    for key in ("tricks", "glossary", "progression", "sources"):
        f.write("const %s = %s;\n" % (key.upper(),
                json.dumps(data[key], ensure_ascii=False, separators=(",", ":"))))

print("%d tricks (%d from the book, %d added on the site, %d enriched), "
      "%d cross-links, %d glossary, %d sources -> %.0f KB"
      % (len(tricks), len(tricks) - len(extra_tricks), len(extra_tricks), enriched, linked,
         len(front["glossary"]), len(front["sources"]), os.path.getsize(OUT) / 1024))
